# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

parameters:
  # defaults for any parameters that are not specified
  name: ''
  vmImage: ''
  use.numba: 'true'


jobs:

- job: ${{ parameters.name }}Test
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      python310_win_latest:
        python.version: '3.10'
      python311_win_latest:
        python.version: '3.11'
      python312_win_latest:
        python.version: '3.12'
      python313_win_latest:
        python.version: '3.12'
    maxParallel: 10

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip "setuptools>=61" wheel
      python -m pip install -r requirements-dev.txt
      python -m pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      python -m pip list
    displayName: 'List Configuration'

  - script: |
      python -m pip install -e . -v --no-build-isolation
    displayName: 'Build Cython Extensions'

  - script: |
      pytest arch --junitxml=junit/test-results.xml -n 2 --durations=25
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
